import { defineConfig } from 'windicss/helpers'
import colors from 'windicss/colors'

export default defineConfig({
  darkMode: 'class',
  attributify: false,
  safelist: [
    'bg-primary-50',
    'bg-secondary-50',
    'bg-success-50',
    'bg-warning-50',
    'bg-danger-50',
    'bg-primary-100',
    'bg-secondary-100',
    'bg-success-100',
    'bg-warning-100',
    'bg-danger-100',
    'bg-primary-200',
    'bg-secondary-200',
    'bg-success-200',
    'bg-warning-200',
    'bg-danger-200',
    'bg-primary-500',
    'bg-secondary-500',
    'bg-success-500',
    'bg-warning-500',
    'bg-danger-500',
    'bg-light-500',
    'bg-light-primary-500',
    'bg-primary-700',
    'bg-secondary-700',
    'bg-success-700',
    'bg-warning-700',
    'bg-danger-700',
    'bg-light-700',
    'bg-light-primary-700',
    'border-primary-500',
    'border-secondary-500',
    'border-success-500',
    'border-warning-500',
    'border-danger-500',
    'text-primary-500',
    'text-secondary-500',
    'text-success-500',
    'text-warning-500',
    'text-danger-500',
    'hover:bg-primary-50',
    'hover:bg-secondary-50',
    'hover:bg-success-50',
    'hover:bg-warning-50',
    'hover:bg-danger-50',
    'hover:bg-primary-100',
    'hover:bg-secondary-100',
    'hover:bg-success-100',
    'hover:bg-warning-100',
    'hover:bg-danger-100',
    'hover:bg-primary-500',
    'hover:bg-secondary-500',
    'hover:bg-success-500',
    'hover:bg-warning-500',
    'hover:bg-danger-500',
    'hover:bg-primary-700',
    'hover:bg-secondary-700',
    'hover:bg-success-700',
    'hover:bg-warning-700',
    'hover:bg-danger-700',
    'hover:bg-light-700',
    'hover:bg-light-primary-700',
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors
        primary: colors.violet,
        secondary: colors.gray,
        success: colors.green,
        warning: colors.amber,
        danger: colors.red,
        link: colors.blue,
        light: {
          500: 'white',
          700: 'var(--color-gray-200)',
        },
        'light-primary': {
          500: 'white',
          700: 'var(--color-violet-200)',
        },
        ...colors,
      },
    },
  },
})
